[package]
name = "becoming-functional-in-rust"
version = "0.1.0"
authors = ["monsieursquirrel"]

[lib]
name = "example_2_1"
path = "chapter_2/example_2_1/customer.rs"

[[bin]]
name = "chapter_10_putting_it_all_together"
path = "chapter_10/putting_it_all_together/main.rs"
